name: GitHub Actions Demo
on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: custom
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      - name: Log into registry
        run: echo "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" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID:v${{ github.run_id }}-dev
          docker push $IMAGE_ID:v${{ github.run_id }}-dev
