name: GitHub Actions Demo
on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: custom
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: zip artifact
        run: zip -r release.zip package* src
        
      