name: GitHub Actions Demo
on:
  push:
    branches:
      - sesion3
env:
  IMAGE_NAME: custom
jobs:
  building:
    runs-on: ubuntu-latest
    env:
      IMAGE=ghcr.io/${{ github.actor }}/nodeapp-demo
    steps:
      - uses: actions/checkout@v2
      - name: build container
        working-directory: ./ejemplos/sesion3
        run: |
          docker build -t nodeapp-demo .
      - name: tag
        run: |
          docker tag nodeapp-demo $IMAGE:${{ github.run_number }}
      - name: login
        run: echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: push
        run: |
          docker push $IMAGE:${{ github.run_number }}